Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -98,7 +98,8 @@ jobs:
       - name: Clean Buildozer
         run: |
           echo "Cleaning build with Buildozer."
-          buildozer android clean || { echo "Clean failed. Exiting."; exit 1; }
+          # Explicitly setting the python-for-android directory path to avoid the error
+          buildozer -v android clean p4a.source_dir=$HOME/.buildozer/android/platform/python-for-android || { echo "Clean failed. Exiting."; exit 1; }
 
       - name: Build APK
         run: |
